name: bulk_overlay
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.0.0
  flutter:
    sdk: flutter
  jpeg_encode: ^1.0.1
  path: ^1.9.1
  provider: ^6.1.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
